services:
  darthvader:
    build: dnsserver
    hostname: darthvader
    networks:
      rededns:
          ipv4_address: 192.168.20.10
    volumes:
      - ./dnsserver/conf/primario/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/primario/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/primario/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/conf/primario/db.galaxia.lan:/etc/bind/db.galaxia.lan
      - ./dnsserver/conf/primario/db.20.168.192:/etc/bind/db.20.168.192
  darthsidious:
    build: dnsserver
    hostname: darthsidious
    dns:
      - 192.168.20.10
      - 192.168.20.11    
    networks:
      rededns:
          ipv4_address: 192.168.20.11
    volumes:
      - ./dnsserver/conf/secundario/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/secundario/named.conf.local:/etc/bind/named.conf.local
  leia:
    build: debian
    hostname: leia
    networks:
      rededns:
        ipv4_address: 192.168.20.12
    volumes:
      - ./dnsserver/conf/leia/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/conf/leia/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/conf/leia/db.imperio.starwars.lan:/etc/bind/db.imperio.starwars.lan
  eq1:
    build: debian
    hostname: eq1
    dns:
      - 192.168.20.10
      - 192.168.20.11
    networks:
      rededns:
          ipv4_address: 192.168.20.100
    volumes:
      - ./debian/conf/eq1/rndc.conf:/etc/bind/rndc.conf
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

